### ISSUE TITLE
A way to remove "new connection from"?

### ISSUE THREAD

**Issue by Dinip** [K-4U/serverQueryExtender#12]
Is there a way to stop this spam? I'm using this mod to export some stats to a graph, like tps, ticktime, players... but since I refresh it every 10s there is so much spam on console/logs.
Thanks
![image](https://user-images.githubusercontent.com/8941012/51493011-b3859500-1dab-11e9-80ba-5fcb2e0051d6.png)

**Comment by K-4U** [comment]
Hah, woops. That isn't supposed to be there. What version of mc are you running?

**Comment by Dinip** [comment]
yeah... 1.12.2
on curse the mod is compatible with 1.12.1 so... 
ServerInfoProvider-1.12.1-3.0.36-universal.jar

**Comment by K-4U** [comment]
New version has been uploaded to curse, though untested.

**Comment by Dinip** [comment]
yep... 
![image](https://user-images.githubusercontent.com/8941012/51494448-94d5cd00-1db0-11e9-83bb-8a659303ad08.png)

**Comment by Dinip** [comment]
nvm, my bad... the problem was mine :( 
I'm sorry

**Comment by K-4U** [comment]
Alright, so it's working now? :)

**Comment by Dinip** [comment]
So far so good! Thank you 👍
