### ISSUE TITLE
Deadlocking and lag /w SIP

### ISSUE THREAD

**Issue by ghost** [K-4U/serverQueryExtender#9]
Severe lag and repeat deadlocks with SIP/K4Lib installed, disabling the mods resolved the problem.
Crash Report: http://paste.creeperhost.net/view/af280cd1
FTB Infinity Lite: 1.8.0
Minecraft: 1.10.2

**Comment by K-4U** [comment]
I noticed that you're not running the latest version of SIP. Could you try updating to 2.0.31 and try again?

**Comment by K-4U** [comment]
Closing because it doesn't seem to occur anymore
